/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */

#include "pypto/codegen/cce/cce_codegen.h"

#include <cstddef>
#include <ios>
#include <map>
#include <memory>
#include <optional>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include "pypto/backend/common/backend.h"
#include "pypto/backend/common/backend_config.h"
#include "pypto/codegen/orchestration/orchestration_codegen.h"
#include "pypto/core/error.h"
#include "pypto/core/logging.h"
#include "pypto/ir/expr.h"
#include "pypto/ir/function.h"
#include "pypto/ir/pipe.h"
#include "pypto/ir/program.h"
#include "pypto/ir/scalar_expr.h"
#include "pypto/ir/stmt.h"
#include "pypto/ir/type.h"

namespace pypto {
namespace codegen {

const char KERNEL_HEADER[] = R"(
#include <cstdint>
#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif
)";

CCECodegen::CCECodegen() : backend_(backend::GetBackend()) {
  auto type = backend::GetBackendType();
  CHECK(type == backend::BackendType::Ascend910B_CCE)
      << "CCECodegen requires Ascend910B_CCE backend, but "
      << (type == backend::BackendType::Ascend910B_PTO ? "Ascend910B_PTO" : "unknown") << " is configured";
}

std::map<std::string, std::string> CCECodegen::Generate(const ir::ProgramPtr& program) {
  CHECK(program != nullptr) << "Cannot generate code for null program";

  std::map<std::string, std::string> files;

  // Separate functions into kernel functions and orchestration functions
  std::vector<ir::FunctionPtr> kernel_functions;
  std::vector<ir::FunctionPtr> orchestration_functions;

  for (const auto& [gvar, func] : program->functions_) {
    INTERNAL_CHECK(func->func_type_ != ir::FunctionType::Opaque)
        << "CCE backend doesn't support Opaque functions : " << func->name_;
    if (func->func_type_ == ir::FunctionType::Orchestration) {
      orchestration_functions.push_back(func);
    } else if (func->func_type_ == ir::FunctionType::Group) {
      // Group functions coordinate AIC + AIV execution; their calls are expanded
      // inline in orchestration codegen. No kernel code is generated for them.
      continue;
    } else {
      kernel_functions.push_back(func);
    }
  }

  // Generate kernel functions (CCE C++ code) to separate .cpp files in kernels/ subdirectory
  for (const auto& func : kernel_functions) {
    std::ostringstream oss;
    oss << "// Kernel Function: " << func->name_ << "\n";
    oss << "// Generated by PyPTO IR Compiler\n\n";
    oss << KERNEL_HEADER << "\n";

    // Add compute_stride helper function
    oss << "// Helper function to compute stride from raw_shapes\n";
    oss << "__aicore__ __attribute__((always_inline)) inline int64_t compute_stride(\n";
    oss << "    __gm__ TensorData* tensor, int dim) {\n";
    oss << "  int64_t stride = 1;\n";
    oss << "  for (int j = dim + 1; j < static_cast<int>(tensor->ndims); j++) {\n";
    oss << "    stride *= static_cast<int64_t>(tensor->raw_shapes[j]);\n";
    oss << "  }\n";
    oss << "  return stride;\n";
    oss << "}\n\n";

    std::string func_code = GenerateFunction(func);
    oss << func_code;

    auto core_type = InferFunctionCoreType(func);
    std::string core_type_str = core_type == ir::CoreType::VECTOR ? "aiv" : "aic";

    std::string filename = "kernels/" + core_type_str + "/" + func->name_ + ".cpp";
    files[filename] = oss.str();
  }

  // Generate orchestration function to orchestration/ subdirectory
  if (!orchestration_functions.empty()) {
    if (orchestration_functions.size() > 1) {
      throw pypto::ValueError("Program should have exactly one orchestration function, got " +
                              std::to_string(orchestration_functions.size()));
    }

    const auto& func = orchestration_functions[0];
    std::ostringstream oss;
    oss << "// Orchestration Function: " << func->name_ << "\n";
    oss << "// Generated by PyPTO IR Compiler\n\n";

    auto orch_result = GenerateOrchestration(program, func);
    oss << orch_result.code;

    std::string filename = "orchestration/" + func->name_ + ".cpp";
    files[filename] = oss.str();

    // Generate config file
    std::string config_code =
        GenerateConfigFile(func->name_, orch_result.func_name_to_id, orch_result.func_name_to_core_type);
    files["kernel_config.py"] = config_code;
  }

  return files;
}

std::string CCECodegen::GenerateConfigFile(
    const std::string& orch_func_name, const std::map<std::string, int>& func_name_to_id,
    const std::map<std::string, ir::CoreType>& func_name_to_core_type) {
  std::ostringstream oss;
  oss << "# Kernel and Orchestration Configuration\n\n";
  oss << "from pathlib import Path\n\n";
  oss << "_ROOT_DIR = Path(__file__).parent\n\n";

  oss << "# Runtime configuration for tensormap_and_ringbuffer\n";
  oss << "# This runtime requires 4 AICPU threads (3 schedulers + 1 orchestrator on thread 3)\n";
  oss << "RUNTIME_CONFIG = {\n";
  oss << "\t\"runtime\": \"tensormap_and_ringbuffer\",\n";
  oss << "\t\"aicpu_thread_num\": 4,\n";
  oss << "\t\"orch_thread_num\": 1,\n";
  oss << "\t\"block_dim\": 24,\n";
  oss << "}\n\n";

  oss << "ORCHESTRATION = {\n\t\"source\": str(_ROOT_DIR / \"orchestration\" / \"" << orch_func_name
      << ".cpp\"),\n"
      << "\t\"function_name\": \"aicpu_orchestration_entry\"\n}\n\n";

  oss << "KERNELS = [\n";
  for (const auto& [name, id] : func_name_to_id) {
    std::string core_type = func_name_to_core_type.at(name) == ir::CoreType::VECTOR ? "aiv" : "aic";
    oss << "\t{\"func_id\": " << id << R"(, "source": str(_ROOT_DIR / "kernels" / ")" << core_type
        << "\" / \"" << name << R"(.cpp"), "core_type": ")" << core_type << "\"},\n";
  }
  oss << "]\n";
  return oss.str();
}

std::string CCECodegen::GenerateFunction(const ir::FunctionPtr& func) {
  CHECK(func != nullptr) << "Cannot generate code for null function";

  // Clear state
  emitter_.Clear();
  context_.Clear();
  global_tensor_counter_ = 0;

  // Generate prologue and body
  GeneratePrologue(func);
  GenerateBody(func);

  return emitter_.GetCode();
}

void CCECodegen::GeneratePrologue(const ir::FunctionPtr& func) {
  // Function signature
  emitter_.EmitLine(
      "extern \"C\" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)");
  emitter_.EmitLine("{");
  emitter_.IncreaseIndent();

  emitter_.EmitLine("// Unpack arguments and type declarations");

  // First pass: Unpack arguments
  for (size_t i = 0; i < func->params_.size(); ++i) {
    const auto& param = func->params_[i];
    const std::string param_name = context_.SanitizeName(param);

    // tensor type parameter and type declaration
    if (auto tensor_type = std::dynamic_pointer_cast<const ir::TensorType>(param->GetType())) {
      // Extract element type
      std::string element_type = tensor_type->dtype_.ToCTypeString();

      // Emit argument unpacking via TensorData* indirection
      std::string tensor_var = param_name + "_tensor";
      emitter_.EmitLine("__gm__ TensorData* " + tensor_var + " = reinterpret_cast<__gm__ TensorData*>(args[" +
                        std::to_string(i) + "]);");
      emitter_.EmitLine("__gm__ " + element_type + "* " + param_name + " = reinterpret_cast<__gm__ " +
                        element_type + "*>(" + tensor_var + "->buffer.addr) + " + tensor_var +
                        "->start_offset;");

      // Register pointer/struct by IR var name for later lookup in tile.load/store
      context_.RegisterPointer(param->name_hint_, param_name);
      context_.RegisterTensorStruct(param->name_hint_, tensor_var);
    } else if (auto scalar_type = std::dynamic_pointer_cast<const ir::ScalarType>(param->GetType())) {
      // Generate scalar type declaration
      std::string cpp_type = scalar_type->dtype_.ToCTypeString();

      // Emit argument unpacking via union converter
      std::string conv_name = param_name + "_conv";
      emitter_.EmitLine("union { uint64_t u64; " + cpp_type + " val; } " + conv_name + ";");
      emitter_.EmitLine(conv_name + ".u64 = args[" + std::to_string(i) + "];");
      emitter_.EmitLine(cpp_type + " " + param_name + " = " + conv_name + ".val;");

      // Register scalar variable
      context_.RegisterVar(param, param_name);
    } else {
      throw pypto::RuntimeError("Unsupported parameter type in function " + func->name_);
    }

    emitter_.EmitLine("");
  }

  // Collect all TileType variables from function body
  std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> tile_vars;
  if (func->body_) {
    tile_vars = CollectTileVariables(func->body_);
  }

  // Generate Tile type definitions and allocations
  if (!tile_vars.empty()) {
    emitter_.EmitLine("// Tile type definitions and allocations");

    for (const auto& [var, tile_type] : tile_vars) {
      // Just use sanitized name (will be registered later in AssignStmt)
      const std::string var_name = context_.SanitizeName(var);

      // Generate Tile type and declaration (memref extracted automatically from tile_type)
      GenerateTileTypeDeclaration(var_name, tile_type);
    }

    emitter_.EmitLine("");
  }

  emitter_.EmitLine("");
}

void CCECodegen::GenerateBody(const ir::FunctionPtr& func) {
  emitter_.EmitLine("// Function body");
  if (func->body_) {
    VisitStmt(func->body_);
  }

  emitter_.DecreaseIndent();
  emitter_.EmitLine("}");
}

void CCECodegen::VisitStmt_(const ir::AssignStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null AssignStmt";
  INTERNAL_CHECK(op->var_ != nullptr) << "Internal error: AssignStmt has null variable";
  INTERNAL_CHECK(op->value_ != nullptr) << "Internal error: AssignStmt has null value";

  // Sanitize and register the variable name
  std::string var_name = context_.SanitizeName(op->var_);
  context_.RegisterVar(op->var_, var_name);

  // Set context for expression visitor (dual-mode pattern)
  current_target_var_ = var_name;
  current_expr_value_ = "";

  // Dispatch to type-specific expression handler
  VisitExpr(op->value_);

  // If expression was non-Call (returned a value), emit assignment
  // Skip for tensor types — tile.store handles pointer/struct registration
  if (!current_expr_value_.empty()) {
    if (!std::dynamic_pointer_cast<const ir::TensorType>(op->var_->GetType())) {
      emitter_.EmitLine("auto " + var_name + " = " + current_expr_value_ + ";");
    }
    current_expr_value_ = "";
  }

  // Clear context
  current_target_var_ = "";
}

void CCECodegen::VisitStmt_(const ir::EvalStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null EvalStmt";
  INTERNAL_CHECK(op->expr_ != nullptr) << "Internal error: EvalStmt has null expression";

  // EvalStmt: evaluate expression for side effects (e.g., sync operations)
  // Sync ops (set_flag, wait_flag, pipe_barrier) are registered with f_codegen_cce
  // and will be invoked via VisitExpr_(Call)
  VisitExpr(op->expr_);
}

void CCECodegen::VisitStmt_(const ir::ReturnStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null ReturnStmt";
  // For void functions, we don't need to generate anything
  // The function will return implicitly at the closing brace
}

void CCECodegen::VisitStmt_(const ir::YieldStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null YieldStmt";

  if (op->value_.empty()) {
    return;  // No values to yield
  }

  // Visit each yielded expression and collect values
  std::vector<std::string> yielded_values;
  std::vector<ir::VarPtr> yielded_vars;
  for (const auto& expr : op->value_) {
    VisitExpr(expr);
    yielded_values.push_back(current_expr_value_);
    yielded_vars.push_back(std::dynamic_pointer_cast<const ir::Var>(expr));
  }

  // Store in temporary buffers for IfStmt/ForStmt to pick up
  yield_buffer_ = yielded_values;
  yield_var_buffer_ = yielded_vars;
  current_expr_value_ = "";
}

void CCECodegen::VisitStmt_(const ir::IfStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null IfStmt";
  INTERNAL_CHECK(op->condition_ != nullptr) << "Internal error: IfStmt has null condition";
  INTERNAL_CHECK(op->then_body_ != nullptr) << "Internal error: IfStmt has null then_body";

  // Declare and register return variables BEFORE the if statement
  // Tensor return_vars are transparent (no declaration) — only pointer/struct propagation
  for (const auto& return_var : op->return_vars_) {
    if (std::dynamic_pointer_cast<const ir::TensorType>(return_var->GetType())) {
      // Tensor: skip declaration, pointer/struct will be propagated after yield
      continue;
    }

    std::string return_var_name = context_.SanitizeName(return_var);
    context_.RegisterVar(return_var, return_var_name);

    if (auto tile_type = std::dynamic_pointer_cast<const ir::TileType>(return_var->GetType())) {
      GenerateTileTypeDeclaration(return_var_name, tile_type);
    } else if (auto scalar_type = std::dynamic_pointer_cast<const ir::ScalarType>(return_var->GetType())) {
      std::string cpp_type = scalar_type->dtype_.ToCTypeString();
      emitter_.EmitLine(cpp_type + " " + return_var_name + ";");
    } else {
      throw pypto::RuntimeError("Unsupported return_var type in IfStmt");
    }
  }

  if (!op->return_vars_.empty()) {
    emitter_.EmitLine("");
  }

  // Evaluate condition
  VisitExpr(op->condition_);
  std::string condition = current_expr_value_;
  current_expr_value_ = "";

  // Emit if statement
  emitter_.EmitLine("if (" + condition + ") {");
  emitter_.IncreaseIndent();

  // Visit then branch
  VisitStmt(op->then_body_);

  // Assign return variables from then branch yield
  if (!op->return_vars_.empty() && !yield_buffer_.empty()) {
    for (size_t i = 0; i < op->return_vars_.size(); ++i) {
      const auto& return_var = op->return_vars_[i];

      if (std::dynamic_pointer_cast<const ir::TensorType>(return_var->GetType())) {
        // Tensor: propagate pointer/struct from yielded var, no assignment
        if (i < yield_var_buffer_.size() && yield_var_buffer_[i]) {
          auto& yielded_var = yield_var_buffer_[i];
          context_.RegisterPointer(return_var->name_hint_, context_.GetPointer(yielded_var->name_hint_));
          context_.RegisterTensorStruct(return_var->name_hint_,
                                        context_.GetTensorStruct(yielded_var->name_hint_));
        }
      } else {
        std::string return_var_name = context_.SanitizeName(return_var);
        emitter_.EmitLine(return_var_name + " = " + yield_buffer_[i] + ";");
      }
    }
    yield_buffer_.clear();
    yield_var_buffer_.clear();
  }

  emitter_.DecreaseIndent();

  // Emit else branch if present
  if (op->else_body_.has_value()) {
    emitter_.EmitLine("} else {");
    emitter_.IncreaseIndent();

    VisitStmt(*op->else_body_);  // NOLINT(bugprone-unchecked-optional-access)

    // Assign return variables from else branch yield
    if (!op->return_vars_.empty() && !yield_buffer_.empty()) {
      for (size_t i = 0; i < op->return_vars_.size(); ++i) {
        const auto& return_var = op->return_vars_[i];

        if (std::dynamic_pointer_cast<const ir::TensorType>(return_var->GetType())) {
          if (i < yield_var_buffer_.size() && yield_var_buffer_[i]) {
            auto& yielded_var = yield_var_buffer_[i];
            context_.RegisterPointer(return_var->name_hint_, context_.GetPointer(yielded_var->name_hint_));
            context_.RegisterTensorStruct(return_var->name_hint_,
                                          context_.GetTensorStruct(yielded_var->name_hint_));
          }
        } else {
          std::string return_var_name = context_.SanitizeName(return_var);
          emitter_.EmitLine(return_var_name + " = " + yield_buffer_[i] + ";");
        }
      }
      yield_buffer_.clear();
      yield_var_buffer_.clear();
    }

    emitter_.DecreaseIndent();
  }

  emitter_.EmitLine("}");
  emitter_.EmitLine("");
}

void CCECodegen::VisitStmt_(const ir::ForStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null ForStmt";
  INTERNAL_CHECK(op->loop_var_ != nullptr) << "Internal error: ForStmt has null loop_var";
  INTERNAL_CHECK(op->start_ != nullptr) << "Internal error: ForStmt has null start";
  INTERNAL_CHECK(op->stop_ != nullptr) << "Internal error: ForStmt has null stop";
  INTERNAL_CHECK(op->step_ != nullptr) << "Internal error: ForStmt has null step";
  INTERNAL_CHECK(op->body_ != nullptr) << "Internal error: ForStmt has null body";

  // Check consistency: iter_args and return_vars must have same size
  CHECK(op->iter_args_.size() == op->return_vars_.size())
      << "ForStmt iter_args size (" << op->iter_args_.size() << ") must equal return_vars size ("
      << op->return_vars_.size() << ")";

  if (op->kind_ == ir::ForKind::Unroll) {
    LOG_WARN << "ForKind::Unroll loop was not expanded before codegen; "
                "generating sequential loop as fallback";
  }

  // Register loop variable
  std::string loop_var_name = context_.SanitizeName(op->loop_var_);
  context_.RegisterVar(op->loop_var_, loop_var_name);

  // Register iteration arguments (loop-carried values)
  std::vector<std::string> iter_arg_names;
  if (!op->iter_args_.empty()) {
    emitter_.EmitLine("// Loop-carried values initialization");
    for (auto& iter_arg : op->iter_args_) {
      bool is_tensor = std::dynamic_pointer_cast<const ir::TensorType>(iter_arg->GetType()) != nullptr;

      if (is_tensor) {
        // Tensor iter_arg: propagate pointer/struct from init value, no declaration
        auto init_var = std::dynamic_pointer_cast<const ir::Var>(iter_arg->initValue_);
        INTERNAL_CHECK(init_var != nullptr) << "Internal error: tensor iter_arg init must be a Var";
        context_.RegisterPointer(iter_arg->name_hint_, context_.GetPointer(init_var->name_hint_));
        context_.RegisterTensorStruct(iter_arg->name_hint_, context_.GetTensorStruct(init_var->name_hint_));
        iter_arg_names.emplace_back("");  // Placeholder — not used for tensor
      } else {
        std::string iter_arg_name = context_.SanitizeName(iter_arg);
        context_.RegisterVar(iter_arg, iter_arg_name);
        iter_arg_names.push_back(iter_arg_name);

        VisitExpr(iter_arg->initValue_);
        std::string init_value = current_expr_value_;
        current_expr_value_ = "";

        emitter_.EmitLine("auto " + iter_arg_name + " = " + init_value + ";");
      }
    }
    emitter_.EmitLine("");
  }

  // Evaluate loop range
  VisitExpr(op->start_);
  std::string start = current_expr_value_;
  current_expr_value_ = "";

  VisitExpr(op->stop_);
  std::string stop = current_expr_value_;
  current_expr_value_ = "";

  VisitExpr(op->step_);
  std::string step = current_expr_value_;
  current_expr_value_ = "";

  // Emit for loop
  emitter_.EmitLine("for (uint64_t " + loop_var_name + " = " + start + "; " + loop_var_name + " < " + stop +
                    "; " + loop_var_name + " += " + step + ") {");
  emitter_.IncreaseIndent();

  // Visit loop body
  yield_buffer_.clear();
  yield_var_buffer_.clear();
  VisitStmt(op->body_);

  // If iter_args exist and yield was called, assign yielded values
  if (!op->iter_args_.empty() && !yield_buffer_.empty()) {
    for (size_t i = 0; i < op->iter_args_.size(); ++i) {
      bool is_tensor =
          std::dynamic_pointer_cast<const ir::TensorType>(op->iter_args_[i]->GetType()) != nullptr;

      if (is_tensor) {
        // Tensor: propagate pointer/struct from yielded var
        if (i < yield_var_buffer_.size() && yield_var_buffer_[i]) {
          auto& yielded_var = yield_var_buffer_[i];
          context_.RegisterPointer(op->iter_args_[i]->name_hint_,
                                   context_.GetPointer(yielded_var->name_hint_));
          context_.RegisterTensorStruct(op->iter_args_[i]->name_hint_,
                                        context_.GetTensorStruct(yielded_var->name_hint_));
        }
      } else {
        emitter_.EmitLine(iter_arg_names[i] + " = " + yield_buffer_[i] + ";");
      }
    }
  }
  yield_buffer_.clear();
  yield_var_buffer_.clear();

  emitter_.DecreaseIndent();
  emitter_.EmitLine("}");
  emitter_.EmitLine("");

  // Register return variables
  // (return_vars represent the final values of iter_args after loop completion)
  if (!op->return_vars_.empty()) {
    for (size_t i = 0; i < op->return_vars_.size(); ++i) {
      const auto& return_var = op->return_vars_[i];
      bool is_tensor = std::dynamic_pointer_cast<const ir::TensorType>(return_var->GetType()) != nullptr;

      if (is_tensor) {
        // Tensor: propagate pointer/struct from iter_arg
        context_.RegisterPointer(return_var->name_hint_, context_.GetPointer(op->iter_args_[i]->name_hint_));
        context_.RegisterTensorStruct(return_var->name_hint_,
                                      context_.GetTensorStruct(op->iter_args_[i]->name_hint_));
      } else if (i < iter_arg_names.size()) {
        context_.RegisterVar(return_var, iter_arg_names[i]);
      } else {
        throw pypto::RuntimeError("ForStmt return_var has no corresponding iter_arg");
      }
    }
  }
}

void CCECodegen::VisitStmt_(const ir::WhileStmtPtr& op) {
  throw pypto::RuntimeError("WhileStmt codegen not yet implemented");
}

// ========================================================================
// Expression Visitor Methods - Dual-Mode Pattern
// ========================================================================
// - Statement-Emitting Mode (Call): Uses current_target_var_, emits instructions
// - Value-Returning Mode (others): Sets current_expr_value_ with inline C++ code

// ---- Leaf Nodes ----

void CCECodegen::VisitExpr_(const ir::VarPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Var";
  current_expr_value_ = context_.GetVarName(op);
}

void CCECodegen::VisitExpr_(const ir::IterArgPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null IterArg";
  // IterArg inherits from Var, treated same way
  current_expr_value_ = context_.GetVarName(std::dynamic_pointer_cast<const ir::Var>(op));
}

void CCECodegen::VisitExpr_(const ir::ConstIntPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null ConstInt";
  current_expr_value_ = std::to_string(op->value_);
}

void CCECodegen::VisitExpr_(const ir::ConstFloatPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null ConstFloat";
  current_expr_value_ = std::to_string(op->value_);
}

void CCECodegen::VisitExpr_(const ir::ConstBoolPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null ConstBool";
  current_expr_value_ = op->value_ ? "true" : "false";
}

void CCECodegen::VisitExpr_(const ir::TupleGetItemExprPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null TupleGetItemExpr";
  VisitExpr(op->tuple_);
  std::string tuple_name = current_expr_value_;
  current_expr_value_ = tuple_name + "[" + std::to_string(op->index_) + "]";
}

// ========================================================================
// CodegenBase interface and CCE-specific helper methods
// ========================================================================

std::string CCECodegen::GetExprAsCode(const ir::ExprPtr& expr) {
  VisitExpr(expr);
  return current_expr_value_;
}

void CCECodegen::Emit(const std::string& line) { emitter_.EmitLine(line); }

std::string CCECodegen::GetTypeString(const DataType& dtype) const { return dtype.ToCTypeString(); }

int64_t CCECodegen::GetConstIntValue(const ir::ExprPtr& expr) { return ExtractConstInt(expr); }

std::string CCECodegen::GetVarName(const ir::VarPtr& var) { return context_.GetVarName(var); }

std::string CCECodegen::GetPointer(const std::string& var_name) { return context_.GetPointer(var_name); }

void CCECodegen::RegisterOutputPointer(const std::string& output_var_name, const std::string& ptr_name) {
  context_.RegisterPointer(output_var_name, ptr_name);
}

std::string CCECodegen::GetTensorStruct(const std::string& var_name) {
  return context_.GetTensorStruct(var_name);
}

void CCECodegen::RegisterOutputTensorStruct(const std::string& output_var_name,
                                            const std::string& struct_name) {
  context_.RegisterTensorStruct(output_var_name, struct_name);
}

// ========================================================================
// Call Expression Visitor (uses operator registry codegen functions)
// ========================================================================

void CCECodegen::VisitExpr_(const ir::CallPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Call";

  CHECK(backend_ != nullptr) << "CCE backend must not be null";
  const auto* op_info = backend_->GetOpInfo(op->op_->name_);
  if (op_info == nullptr) {
    ThrowNoCodegenForCall(op->op_->name_);
  }
  std::string result = op_info->codegen_func(op, *this);
  current_expr_value_ = result;
}

// ---- Binary Operators ----

#define IMPLEMENT_BINARY_OP(OpType, OpName, CppOp)                        \
  void CCECodegen::VisitExpr_(const ir::OpType##Ptr& op) {                \
    INTERNAL_CHECK(op != nullptr) << "Internal error: null " << (OpName); \
    VisitExpr(op->left_);                                                 \
    std::string left = current_expr_value_;                               \
    VisitExpr(op->right_);                                                \
    std::string right = current_expr_value_;                              \
    current_expr_value_ = "(" + left + " " + (CppOp) + " " + right + ")"; \
  }

// Arithmetic operators
IMPLEMENT_BINARY_OP(Add, "Add", "+")
IMPLEMENT_BINARY_OP(Sub, "Sub", "-")
IMPLEMENT_BINARY_OP(Mul, "Mul", "*")
IMPLEMENT_BINARY_OP(FloorDiv, "FloorDiv", "/")
IMPLEMENT_BINARY_OP(FloorMod, "FloorMod", "%")
IMPLEMENT_BINARY_OP(FloatDiv, "FloatDiv", "/")

// Comparison operators
IMPLEMENT_BINARY_OP(Eq, "Eq", "==")
IMPLEMENT_BINARY_OP(Ne, "Ne", "!=")
IMPLEMENT_BINARY_OP(Lt, "Lt", "<")
IMPLEMENT_BINARY_OP(Le, "Le", "<=")
IMPLEMENT_BINARY_OP(Gt, "Gt", ">")
IMPLEMENT_BINARY_OP(Ge, "Ge", ">=")

// Logical operators
IMPLEMENT_BINARY_OP(And, "And", "&&")
IMPLEMENT_BINARY_OP(Or, "Or", "||")
IMPLEMENT_BINARY_OP(Xor, "Xor", "^")

// Bitwise operators
IMPLEMENT_BINARY_OP(BitAnd, "BitAnd", "&")
IMPLEMENT_BINARY_OP(BitOr, "BitOr", "|")
IMPLEMENT_BINARY_OP(BitXor, "BitXor", "^")
IMPLEMENT_BINARY_OP(BitShiftLeft, "BitShiftLeft", "<<")
IMPLEMENT_BINARY_OP(BitShiftRight, "BitShiftRight", ">>")

#undef IMPLEMENT_BINARY_OP

// Special binary operators (function calls)
void CCECodegen::VisitExpr_(const ir::MinPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Min";
  VisitExpr(op->left_);
  std::string left = current_expr_value_;
  VisitExpr(op->right_);
  std::string right = current_expr_value_;
  current_expr_value_ = "min(" + left + ", " + right + ")";
}

void CCECodegen::VisitExpr_(const ir::MaxPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Max";
  VisitExpr(op->left_);
  std::string left = current_expr_value_;
  VisitExpr(op->right_);
  std::string right = current_expr_value_;
  current_expr_value_ = "max(" + left + ", " + right + ")";
}

void CCECodegen::VisitExpr_(const ir::PowPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Pow";
  VisitExpr(op->left_);
  std::string left = current_expr_value_;
  VisitExpr(op->right_);
  std::string right = current_expr_value_;
  current_expr_value_ = "pow(" + left + ", " + right + ")";
}

// ---- Unary Operators ----

#define IMPLEMENT_UNARY_OP(OpType, OpName, CppOp)                                 \
  void CCECodegen::VisitExpr_(const ir::OpType##Ptr& op) {                        \
    INTERNAL_CHECK(op != nullptr) << "Internal error: null " << (OpName);         \
    VisitExpr(op->operand_);                                                      \
    current_expr_value_ = std::string("(") + (CppOp) + current_expr_value_ + ")"; \
  }

IMPLEMENT_UNARY_OP(Neg, "Neg", "-")
IMPLEMENT_UNARY_OP(Not, "Not", "!")
IMPLEMENT_UNARY_OP(BitNot, "BitNot", "~")

#undef IMPLEMENT_UNARY_OP

// Special unary operators
void CCECodegen::VisitExpr_(const ir::AbsPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Abs";
  VisitExpr(op->operand_);
  std::string operand = current_expr_value_;
  current_expr_value_ = "abs(" + operand + ")";
}

void CCECodegen::VisitExpr_(const ir::CastPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Cast";
  VisitExpr(op->operand_);
  std::string operand = current_expr_value_;

  auto scalar_type = std::dynamic_pointer_cast<const ir::ScalarType>(op->GetType());
  CHECK(scalar_type != nullptr) << "Cast target must be ScalarType";

  std::string cpp_type = scalar_type->dtype_.ToCTypeString();
  current_expr_value_ = "((" + cpp_type + ")" + operand + ")";
}

// ========================================================================
// End of Expression Visitor Methods
// ========================================================================

int64_t CCECodegen::ExtractConstInt(const ir::ExprPtr& expr) {
  auto const_int = std::dynamic_pointer_cast<const ir::ConstInt>(expr);
  CHECK(const_int != nullptr) << "Expected constant integer expression";
  return const_int->value_;
}

namespace {

/**
 * @brief Helper visitor for collecting TileType variables from IR
 *
 * Traverses the IR tree and collects all variables with TileType.
 * Uses the visitor pattern for clean, extensible traversal.
 */
class TileCollector : public ir::IRVisitor {
 public:
  std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> tile_vars_;

  void VisitStmt_(const ir::AssignStmtPtr& op) override {
    // Check if the assigned variable has TileType
    auto tile_type = std::dynamic_pointer_cast<const ir::TileType>(op->var_->GetType());
    if (tile_type) {
      tile_vars_.emplace_back(op->var_, tile_type);
    }
  }
};

}  // namespace

std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> CCECodegen::CollectTileVariables(
    const ir::StmtPtr& stmt) {
  if (!stmt) {
    return {};
  }

  TileCollector collector;
  collector.VisitStmt(stmt);
  return collector.tile_vars_;
}

std::vector<int64_t> CCECodegen::ExtractShapeDimensions(const std::vector<ir::ExprPtr>& shape_exprs) {
  std::vector<int64_t> dims;
  dims.reserve(shape_exprs.size());
  for (const auto& expr : shape_exprs) {
    dims.push_back(ExtractConstInt(expr));
  }
  return dims;
}

std::string CCECodegen::FormatAddressHex(int64_t addr) {
  std::ostringstream oss;
  oss << "0x" << std::hex << addr;
  return oss.str();
}

void CCECodegen::GenerateTileTypeDeclaration(const std::string& var_name, const ir::TileTypePtr& tile_type) {
  INTERNAL_CHECK(!var_name.empty()) << "Internal error: var_name cannot be empty";
  INTERNAL_CHECK(tile_type != nullptr) << "Internal error: tile_type is null";

  // Extract tile shape dimensions
  std::vector<int64_t> shape_dims = ExtractShapeDimensions(tile_type->shape_);

  // CCE codegen only supports 1D and 2D tiles
  CHECK(shape_dims.size() <= 2) << "CCE codegen only supports 1D and 2D TileType, but got "
                                << shape_dims.size()
                                << " dimensions. Multi-dimensional tiles (>2D) are supported at IR level "
                                << "but not yet in code generation.";

  // Determine tile dimensions (default to 1 if not specified)
  int64_t rows = shape_dims.size() >= 1 ? shape_dims[0] : 1;
  int64_t cols = shape_dims.size() >= 2 ? shape_dims[1] : 1;

  // Generate Tile type alias
  std::string type_alias_name = var_name + "Type";
  std::string tile_type_str = type_converter_.ConvertTileType(tile_type, rows, cols);
  std::ostringstream type_alias;
  type_alias << "using " << type_alias_name << " = " << tile_type_str << ";";
  emitter_.EmitLine(type_alias.str());

  // Generate Tile instance
  std::ostringstream tile_instance;
  tile_instance << type_alias_name << " " << var_name << "(" << rows << ", " << cols << ");";
  emitter_.EmitLine(tile_instance.str());

  // Generate TASSIGN if tile_type has memref
  if (tile_type->memref_.has_value()) {
    int64_t addr =
        ExtractConstInt((*tile_type->memref_)->addr_);  // NOLINT(bugprone-unchecked-optional-access)
    std::ostringstream tassign;
    tassign << "TASSIGN(" << var_name << ", " << FormatAddressHex(addr) << ");";
    emitter_.EmitLine(tassign.str());
  }
}

void CCECodegen::GenerateGlobalTensorTypeDeclaration(
    const std::string& var_name, const ir::TensorTypePtr& tensor_type,
    const std::optional<std::string>& base_pointer, const std::optional<std::string>& tensor_struct_ptr,
    const std::optional<std::vector<ir::ExprPtr>>& access_shape) {
  INTERNAL_CHECK(!var_name.empty()) << "Internal error: var_name cannot be empty";
  INTERNAL_CHECK(tensor_type != nullptr) << "Internal error: tensor_type is null";

  // Full tensor dimensions are needed for stride constructor args
  std::vector<int64_t> tensor_dims = ExtractShapeDimensions(tensor_type->shape_);

  // Access shape overrides Shape<>/Stride<> type parameters when available
  std::vector<int64_t> shape_dims =
      access_shape.has_value() ? ExtractShapeDimensions(access_shape.value()) : tensor_dims;

  // Get element type
  std::string element_type = tensor_type->dtype_.ToCTypeString();

  // Generate unique type names for this variable
  std::string shape_type_name = var_name + "ShapeDim5";
  std::string stride_type_name = var_name + "StrideDim5";
  std::string global_type_name = var_name + "Type";

  // Generate Shape type alias
  std::string shape_type = type_converter_.GenerateShapeType(shape_dims);
  std::ostringstream shape_alias;
  shape_alias << "using " << shape_type_name << " = " << shape_type << ";";
  emitter_.EmitLine(shape_alias.str());

  // Generate Stride type alias
  std::string stride_type = type_converter_.GenerateStrideType(shape_dims);
  std::ostringstream stride_alias;
  stride_alias << "using " << stride_type_name << " = " << stride_type << ";";
  emitter_.EmitLine(stride_alias.str());

  // Generate layout
  std::string layout = "Layout::ND";
  if (tensor_type->tensor_view_.has_value()) {
    auto tensor_layout = tensor_type->tensor_view_.value().layout;
    layout = "Layout::" + ir::TensorLayoutToString(tensor_layout);
  }

  // Generate GlobalTensor type alias
  std::ostringstream global_type_alias;
  global_type_alias << "using " << global_type_name << " = GlobalTensor<" << element_type << ", "
                    << shape_type_name << ", " << stride_type_name << ", " << layout << ">;";
  emitter_.EmitLine(global_type_alias.str());

  // Generate GlobalTensor instance
  std::ostringstream global_instance;
  global_instance << global_type_name << " " << var_name << "(";
  if (base_pointer.has_value()) {
    global_instance << base_pointer.value();
  }
  if (tensor_struct_ptr.has_value()) {
    global_instance << ", {}, {";
    for (size_t i = 0; i < shape_dims.size(); i++) {
      // For DN layout, swap the last two stride indices to match transposed memory order
      size_t stride_idx = i;
      if (layout == "Layout::DN" && shape_dims.size() >= 2) {
        if (i == shape_dims.size() - 2) {
          stride_idx = shape_dims.size() - 1;
        } else if (i == shape_dims.size() - 1) {
          stride_idx = shape_dims.size() - 2;
        }
      }
      global_instance << "compute_stride(" << tensor_struct_ptr.value() << ", " << std::to_string(stride_idx)
                      << ")";
      if (i != shape_dims.size() - 1) {
        global_instance << ", ";
      }
    }
    global_instance << "}";
  }
  global_instance << ");";
  emitter_.EmitLine(global_instance.str());

  // Register pointer mapping if base_pointer provided
  if (base_pointer.has_value()) {
    context_.RegisterPointer(var_name, base_pointer.value());
  }

  // Register both pointer and Tensor struct mappings if provided
  if (tensor_struct_ptr.has_value()) {
    // Register Tensor struct pointer for stride access
    context_.RegisterTensorStruct(var_name, tensor_struct_ptr.value());
  }
}

}  // namespace codegen

}  // namespace pypto
