# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""
Golden script writer for the PyPTO runtime module.

Generates a ``golden.py`` file compatible with Simpler's CodeRunner from a list
of :class:`TensorSpec` objects and a user-supplied golden function.

Generated file format::

    import ctypes
    import torch

    __outputs__ = ["out"]
    RTOL = 1e-5
    ATOL = 1e-5

    def generate_inputs(params):
        query = torch.randn((32, 128), dtype=torch.bfloat16)
        out   = torch.zeros((32, 128), dtype=torch.float32)
        return [
            ("query", query),
            ("out", out),
            ("size_query", ctypes.c_int64(query.nbytes)),
            ("size_out",   ctypes.c_int64(out.nbytes)),
        ]

    def compute_golden(tensors, params):
        tensors["out"][:] = tensors["query"].float().sum(dim=-1, keepdim=True)
"""

import inspect
import textwrap
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import torch  # type: ignore[import]

from .tensor_spec import TensorSpec


def write_golden(
    tensor_specs: list[TensorSpec],
    golden_fn: Callable,
    output_path: Path,
    rtol: float = 1e-5,
    atol: float = 1e-5,
) -> Path:
    """Generate and write a ``golden.py`` file for Simpler's CodeRunner.

    Args:
        tensor_specs: Ordered list of tensor specifications matching the program's
            parameter list.
        golden_fn: A callable with signature ``(tensors, params)`` that computes
            expected outputs in-place (writes to ``tensors[output_name]``).
        output_path: Destination path for the generated file.
        rtol: Relative tolerance used by CodeRunner for result comparison.
        atol: Absolute tolerance used by CodeRunner for result comparison.

    Returns:
        The resolved ``output_path`` after writing.
    """
    content = _generate_golden_source(tensor_specs, golden_fn, rtol, atol)
    output_path = Path(output_path)
    output_path.write_text(content, encoding="utf-8")
    return output_path


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _generate_golden_source(
    tensor_specs: list[TensorSpec],
    golden_fn: Callable,
    rtol: float,
    atol: float,
) -> str:
    """Build the full content of golden.py as a string."""
    output_names = [spec.name for spec in tensor_specs if spec.is_output]

    lines: list[str] = [
        '"""',
        "Auto-generated golden script — do not edit by hand.",
        "",
        "Generated by pypto.runtime.golden_writer",
        '"""',
        "",
        "import ctypes",
        "import struct",
        "import torch",
        "",
        f"__outputs__ = {output_names!r}",
        f"RTOL = {rtol}",
        f"ATOL = {atol}",
        "",
        "def generate_inputs(params):",
        '    """Generate inputs as a list of (name, value) tuples."""',
    ]

    # Tensor variable declarations
    for spec in tensor_specs:
        lines.append(f"    {spec.name} = {_init_expr(spec)}")

    lines.append("")
    lines.append("    return [")
    for spec in tensor_specs:
        lines.append(f'        ("{spec.name}", {spec.name}),')
    for spec in tensor_specs:
        lines.append(f'        ("size_{spec.name}", ctypes.c_int64({spec.name}.nbytes)),')
    lines.append("    ]")
    lines.append("")
    lines.append("")

    # compute_golden extracted from golden_fn source
    compute_golden_src = _extract_compute_golden(golden_fn)
    lines.extend(compute_golden_src.splitlines())
    lines.append("")

    return "\n".join(lines)


def _init_expr(spec: TensorSpec) -> str:
    """Return the Python expression (string) used to initialise this tensor in golden.py."""
    import torch  # type: ignore[import]  # noqa: PLC0415

    dtype_str = _torch_dtype_str(spec.dtype)
    shape_str = repr(tuple(spec.shape))

    # Outputs are always zero-initialised; their content is set by compute_golden.
    if spec.is_output or spec.init_value is None:
        return f"torch.zeros({shape_str}, dtype={dtype_str})"

    iv = spec.init_value

    if isinstance(iv, (int, float)):
        return f"torch.full({shape_str}, {iv!r}, dtype={dtype_str})"

    if isinstance(iv, torch.Tensor):
        return _tensor_literal_expr(iv, shape_str, dtype_str)

    if callable(iv):
        # Supported torch factory functions can be reproduced literally.
        if iv is torch.randn:
            return f"torch.randn({shape_str}, dtype={dtype_str})"
        if iv is torch.rand:
            return f"torch.rand({shape_str}, dtype={dtype_str})"
        if iv is torch.zeros:
            return f"torch.zeros({shape_str}, dtype={dtype_str})"
        if iv is torch.ones:
            return f"torch.ones({shape_str}, dtype={dtype_str})"
        raise ValueError(
            f"Callable init_value {iv!r} for tensor {spec.name!r} is not supported by "
            "golden_writer. Use a scalar, a torch.Tensor, or one of: "
            "torch.randn, torch.rand, torch.zeros, torch.ones."
        )

    raise TypeError(f"Unsupported init_value type {type(iv)!r} for tensor {spec.name!r}")


def _tensor_literal_expr(tensor: "torch.Tensor", shape_str: str, dtype_str: str) -> str:
    """Generate an inline expression for a concrete torch.Tensor init_value."""
    import torch  # type: ignore[import]  # noqa: PLC0415

    if tensor.numel() == 0:
        return f"torch.zeros({shape_str}, dtype={dtype_str})"

    # Constant tensor
    if torch.all(tensor == tensor.flatten()[0]):
        val = tensor.flatten()[0].item()
        if val == 0.0:
            return f"torch.zeros({shape_str}, dtype={dtype_str})"
        if val == 1.0:
            return f"torch.ones({shape_str}, dtype={dtype_str})"
        return f"torch.full({shape_str}, {val!r}, dtype={dtype_str})"

    # Identity matrix
    if tensor.ndim == 2 and tensor.shape[0] == tensor.shape[1]:
        if torch.allclose(tensor.float(), torch.eye(tensor.shape[0])):
            return f"torch.eye({tensor.shape[0]}, dtype={dtype_str})"

    # Small tensor: inline list literal
    if tensor.numel() <= 100:
        return f"torch.tensor({tensor.tolist()!r}, dtype={dtype_str})"

    # Large tensor: fall back to zeros with a warning comment
    return (
        f"torch.zeros({shape_str}, dtype={dtype_str})  "
        f"# WARNING: tensor too large ({tensor.numel()} elements) to inline; "
        "replace with actual data."
    )


def _torch_dtype_str(dtype: "torch.dtype") -> str:
    """Return the string representation of a torch dtype (e.g. 'torch.float32')."""
    import torch  # type: ignore[import]  # noqa: PLC0415

    _map: dict[torch.dtype, str] = {
        torch.float32: "torch.float32",
        torch.float16: "torch.float16",
        torch.bfloat16: "torch.bfloat16",
        torch.float64: "torch.float64",
        torch.int8: "torch.int8",
        torch.int16: "torch.int16",
        torch.int32: "torch.int32",
        torch.int64: "torch.int64",
        torch.bool: "torch.bool",
    }
    result = _map.get(dtype)
    if result is None:
        raise ValueError(f"Unsupported dtype {dtype!r} in TensorSpec")
    return result


def _extract_compute_golden(golden_fn: Callable) -> str:
    """Extract source of *golden_fn* and rename it to ``compute_golden``.

    The resulting string is a properly-indented top-level function definition
    named ``compute_golden`` with the same body as *golden_fn*.

    Args:
        golden_fn: User-provided golden function (any name, signature ``(tensors, params)``).

    Returns:
        Source code for ``compute_golden(tensors, params)`` as a string.
    """
    try:
        source = inspect.getsource(golden_fn)
    except (TypeError, OSError) as exc:
        raise RuntimeError(
            f"Cannot extract source code from golden function {golden_fn!r}. "
            "Ensure it is defined in a .py file (not in a REPL or dynamically)."
        ) from exc

    # Remove extra leading indentation (e.g. if defined inside a class or function)
    source = textwrap.dedent(source)

    # Rename the function definition line to compute_golden.
    original_name = golden_fn.__name__
    lines = source.splitlines()
    renamed_lines: list[str] = []
    for line in lines:
        if line.lstrip().startswith(f"def {original_name}("):
            renamed_lines.append(line.replace(f"def {original_name}(", "def compute_golden(", 1))
        else:
            renamed_lines.append(line)

    return "\n".join(renamed_lines)
